version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/coffeBreak?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_PASSWORD: root
  SPRING_DATASOURCE_USERNAME: root
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_data:/var/lib/mysql
    mem_limit: 512m

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8585:8080
    mem_limit: 128m
  coffebreak-coffe:
    image: milton668/coffebreak-coffe:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      <<: *database-variables
    mem_limit: 512m

volumes:
  devdojo_data: